version: "3"
services:
  frontend:
    build: ./CRAFT-frontend
    image: frontend:latest
    ports:
      - 80:8081

  backend:
    build: ./CRAFT-backend
    image: backend:latest
    expose:
      - 8080
    volumes:
      - mod-data:/backend/data

volumes:
  mod-data: